-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deletedEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deletedPhone" TEXT;
